/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: Chaitanya Krishnan (https://sketchfab.com/chaitanyak)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/85683027f167491a93c106e45ebb3f58
title: Scorp Mech
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Mech(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/mech.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, -1.84]} rotation={[1.79, 0, 0]}>
          <mesh material={materials.low_rez} geometry={nodes.low_rez_0.geometry} />
          <mesh material={materials.low_rez} geometry={nodes.low_rez_0.geometry} />
          <mesh material={materials.low_rez} geometry={nodes.low_rez_0.geometry} />
          <mesh material={materials.low_rez} geometry={nodes.low_rez_0.geometry} />
          <mesh material={materials.low_rez} geometry={nodes.low_rez_0.geometry} />
          <mesh material={materials.low_rez} geometry={nodes.low_rez_0.geometry} />
          <mesh material={materials.low_rez} geometry={nodes.low_rez_0.geometry} />
          <mesh material={materials.low_rez} geometry={nodes.low_rez_0.geometry} />
          <mesh material={materials.low_rez} geometry={nodes.low_rez_0.geometry} />
          <mesh material={materials.low_rez} geometry={nodes.low_rez_0.geometry} />
        </group>
        <group position={[0, 4.18, -6.3]} scale={[33.14, 33.14, 33.14]}>
          <mesh material={materials.shadow} geometry={nodes.shadow_0.geometry} />
        </group>
      </group>
    </group>
  )
}
